# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=4, verbose_name='chave')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cancelado_as', models.DateTimeField(blank=True, null=True, verbose_name='cancelado \xe0s..')),
            ],
        ),
        migrations.CreateModel(
            name='ContaDeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidade', models.IntegerField(choices=[(0, 'n\xe3o reponda'), (1, 'contato')], verbose_name='responsabilidade')),
                ('servidor', models.CharField(max_length=256, verbose_name='servidor')),
                ('porta', models.IntegerField(verbose_name='porta')),
                ('usuario', models.CharField(max_length=128, verbose_name='usu\xe1rio')),
                ('senha', models.CharField(max_length=128, verbose_name='senha')),
                ('tls', models.BooleanField(default=False, verbose_name='TLS?')),
                ('ssl', models.BooleanField(default=False, verbose_name='SSL?')),
                ('campo_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'conta de e-mail',
                'verbose_name_plural': 'contas de e-mail',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(blank=True, max_length=8, verbose_name='chave')),
                ('para_email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('assunto', models.CharField(max_length=255, verbose_name='assunto')),
                ('corpo', models.TextField(verbose_name='corpo')),
                ('corpo_html', models.TextField(blank=True, verbose_name='corpo HTML')),
                ('enviar_as', models.DateTimeField(null=True, verbose_name='enviar \xe0s')),
                ('processado', models.DateTimeField(null=True, verbose_name='processado \xe0s..')),
                ('enviado', models.DateTimeField(null=True, verbose_name='enviado \xe0s..')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.ContaDeEmail')),
            ],
            options={
                'verbose_name': 'e-mail',
                'verbose_name_plural': 'e-mails',
            },
        ),
    ]
