# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='enviar_as',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enviar \xe0s'),
        ),
    ]
