# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Aniversario')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('arquivo', models.FileField(upload_to=b'')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Missao'),
        ),
        migrations.AddField(
            model_name='aniversario',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Missao'),
        ),
    ]
