# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('apelo', models.TextField(blank=True, verbose_name='apelo')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('descricao', models.CharField(blank=True, max_length=140, verbose_name='Descri\xe7\xe3o')),
                ('arquivo', models.FileField(upload_to=b'')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='t\xedtulo')),
                ('beneficiado', models.CharField(max_length=255, verbose_name='beneficiado')),
                ('descricao', models.TextField(verbose_name='descri\xe7\xe3o')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('meta', models.FloatField(verbose_name='meta em Reais (R$)')),
            ],
        ),
    ]
