# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Aniversario')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('arquivo', models.FileField(upload_to=b'')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug do titulo')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Missao'),
        ),
    ]
