# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='nucleo.Missao'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='aniversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='nucleo.Aniversario'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pagamento'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aniversario',
            name='missao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Missao'),
        ),
        migrations.AddField(
            model_name='aniversario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniversario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aniversario',
            unique_together=set([('usuario', 'ano')]),
        ),
    ]
