# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20160704_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='descricao',
            field=models.CharField(default='test', max_length=140, verbose_name='Descri\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
