# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_media_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='meta',
            field=models.FloatField(default=0, verbose_name='meta em reais'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='descricao',
            field=models.TextField(verbose_name='descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='t\xedtulo'),
        ),
    ]
