# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20160712_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversario',
            name='finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
