# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20160706_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missao',
            name='meta',
            field=models.FloatField(verbose_name='meta em Reais (R$)'),
        ),
    ]
