# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_aniversario_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniversarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
