# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20160718_1333'),
        ('nucleo', '0003_auto_20160716_1402'),
    ]

    operations = [
    ]
