# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20160718_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem aos doadores')),
                ('opniao', models.TextField(verbose_name='Opni\xe3o sobre servi\xe7o')),
                ('aniversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Aniversario')),
            ],
        ),
    ]
