# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20160707_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='beneficiado',
            field=models.CharField(default='padr\xe3o', max_length=255, verbose_name='beneficiado'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aniversario',
            unique_together=set([('usuario', 'ano')]),
        ),
    ]
