# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20160721_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversario',
            name='feeback_liberado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
