# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20160707_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 8, 11, 20, 31, 104918, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
