# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_doacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniversario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='aniversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='nucleo.Aniversario'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
