# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_aniversario_feeback_liberado'),
        ('nucleo', '0006_merge'),
    ]

    operations = [
    ]
