# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20160721_1857'),
        ('nucleo', '0009_auto_20160721_1705'),
    ]

    operations = [
    ]
