# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_aniversario_imagem_divulgacao_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversario',
            name='imagem_divulgacao_fb',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
