# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_auto_20160726_1215'),
        ('nucleo', '0013_auto_20160727_0734'),
    ]

    operations = [
    ]
