# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_auto_20160727_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aniversario',
            old_name='feeback_liberado',
            new_name='feedback_liberado',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='financeiro.Pagamento'),
        ),
    ]
