# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=128, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug do nome')),
                ('data_de_nascimento', models.DateTimeField(blank=True, null=True, verbose_name='data de nascimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='foto')),
                ('e_senha_randomica', models.BooleanField(default=False, verbose_name='a senha ainda \xe9 randomica?')),
                ('e_equipe', models.BooleanField(default=False, verbose_name='\xe9 da equipe?')),
                ('data_ativacao_email', models.DateTimeField(null=True, verbose_name='data de ativa\xe7\xe3o do e-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
        ),
    ]
