# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoDeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(blank=True, max_length=16, verbose_name='chave')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao_de_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
