# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_pagseguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_pagseguro',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do PagSeguro'),
        ),
    ]
