# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_confirmacaodeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacaodeemail',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao_de_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
