# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20160721_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_ddd',
            field=models.IntegerField(null=True, verbose_name='DDD do n\xfamero do telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_numero',
            field=models.IntegerField(null=True, verbose_name='n\xfamero do telefone sem DDD'),
        ),
    ]
