# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20160705_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaodeemail',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 5, 20, 31, 2, 128148, tzinfo=utc), verbose_name='data de solicita\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
