# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20160722_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='migrado',
            field=models.BooleanField(default=False),
        ),
    ]
