# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20160705_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_ativacao_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de ativa\xe7\xe3o do e-mail'),
        ),
    ]
