# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_migrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaodeemail',
            name='migrado',
            field=models.BooleanField(default=False),
        ),
    ]
