# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_confirmacaodeemail_migrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacaodeemail',
            name='migrado',
        ),
    ]
