# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('usuarios', '0006_auto_20160706_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaodeemail',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes_de_email', to='emails.Email'),
        ),
    ]
