# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_confirmacaodeemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacaodeemail',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes_de_email', to='emails.Email'),
        ),
    ]
