# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_confirmacaodeemail_migrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone_ddd',
            field=models.IntegerField(blank=True, null=True, verbose_name='DDD do n\xfamero do telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='n\xfamero do telefone sem DDD'),
        ),
    ]
