# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20160706_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='e_senha_randomica',
        ),
    ]
