# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_e_senha_randomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
