# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20160706_0349'),
        ('usuarios', '0010_auto_20160706_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperarSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(blank=True, max_length=16, unique=True, verbose_name='chave')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperacaoes_de_senha', to='emails.Email')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
