# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_recuperarsenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperarsenha',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes_de_senha', to=settings.AUTH_USER_MODEL),
        ),
    ]
