# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'aguardando pagamento'), (1, 'dispon\xedvel')], default=0)),
            ],
        ),
    ]
