# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagseguro', '0002_auto_20150506_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'aguardando pagamento'), (1, 'dispon\xedvel')], default=0)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagseguro.Checkout')),
            ],
        ),
    ]
