# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0002_auto_20150506_0220'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagseguro.Checkout'),
        ),
    ]
