# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_aniversario_finalizado'),
        ('financeiro', '0002_auto_20160711_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Realizado'), (1, 'Aguardando')])),
                ('aniversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Aniversario')),
            ],
        ),
    ]
