# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='status',
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de realiza\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 18, 12, 21, 35, 670620, tzinfo=utc), verbose_name='Data de solicita\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='aniversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniversario_transacao', to='nucleo.Aniversario'),
        ),
    ]
