# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20160718_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='boleto_link',
            field=models.URLField(blank=True, verbose_name='Link para o boleto'),
        ),
    ]
