# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_pagamento_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_por_cartao', to='pagseguro.Checkout'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagseguro.Checkout'),
        ),
    ]
